version: '3.8'

services:
  # 1. BASE DE DATOS POSTGRESQL
  db:
    image: postgres:16-alpine
    container_name: citt_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cittdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Santiago
    volumes:
      # Guarda la info de la BD en un volumen de Docker para no perder datos si se apaga
      - postgres_data:/var/lib/postgresql/data

  # 2. BACKEND (Spring Boot)
  backend:
    build:
      context: ./citt-backend
      dockerfile: Dockerfile
    container_name: citt_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Le pasamos variables de entorno que Spring Boot ya entiende
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cittdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=tu_clave_secreta_super_segura_para_el_citt_duoc
      - PRODUCTION=true
      - TZ=America/Santiago
    depends_on:
      - db # Espera a que postgres encienda antes de iniciar

  # 3. FRONTEND (React + Nginx)
  frontend:
    build:
      context: ./citt-frontend
      dockerfile: Dockerfile
    container_name: citt_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend # Espera a que el backend encienda antes de iniciar

# Definimos el volumen persistente
volumes:
  postgres_data: