spring.application.name=backend

# --- CONFIGURACIÓN BASE DE DATOS (H2 - LOCAL) ---
spring.datasource.url=jdbc:h2:mem:cittdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

# --- CONFIGURACIÓN BASE DE DATOS (POSTGRESQL - PRODUCCIÓN) ---
# Descomenta esto y comenta lo de H2 cuando conectes Postgres
# spring.datasource.url=jdbc:postgresql://localhost:5432/cittdb
# spring.datasource.driverClassName=org.postgresql.Driver
# spring.datasource.username=tu_usuario_postgres
# spring.datasource.password=tu_clave_postgres
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update

# JWT Secret Key (Must be at least 256-bit long for HS256)
jwt.secret=${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
jwt.expiration=86400000


# Reemplaza con tus datos reales para que funcione
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chrrfran@gmail.com
spring.mail.password=jhwhxtqwphfriags

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true